# Site settings
author: Nathan
title: My Blog
header-img: img/home-bg.png
email: nathansaint810@gmail.com
copyright_name: Nathan
description: > # this means to ignore newlines until "baseurl:"
  A Blog Day's Night
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  nathan-stamand

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
